# Generated by Django 6.1 on 2026-09-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
    ]
